// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Polypheny-JDBC-Driver/src/main/proto/protointerface.proto

package org.polypheny.jdbc.proto;

public interface FrameOrBuilder extends
    // @@protoc_insertion_point(interface_extends:polypheny.protointerface.Frame)
    com.google.protobuf.MessageOrBuilder {
}
