package org.polypheny.jdbc.proto;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Polypheny-JDBC-Driver/src/main/proto/protointerface.proto

public interface FrameOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.polypheny.jdbc.Frame)
    com.google.protobuf.MessageOrBuilder {
}
