// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Polypheny-JDBC-Driver/src/main/proto/protointerface.proto

package org.polypheny.jdbc.proto;

public interface SimpleSqlQueryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:polypheny.protointerface.SimpleSqlQuery)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string query = 1;</code>
   */
  String getQuery();
  /**
   * <code>string query = 1;</code>
   */
  com.google.protobuf.ByteString
      getQueryBytes();
}
